[workspace]
members = ["engine/core", "engine/gl-renderer", "engine/tools/pack", "game"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Morgan Welsch <welschmorgan@gmail.com>"]
